### ISSUE TITLE
64-bit build?

### ISSUE THREAD

**Issue by ilg-ul** [rmyorston/busybox-w32#36] opened 2015-03-17 21:54 UTC
As mentioned in my previous message, I built BusyBox from sources and since my build scripts are generally prepared to create both 32-bit and 64-bit setup packages, I also compiled BusyBox as a 64-bit application (I know it uses 32-bit windows calls, but it is still more convenient on 64-bit machines).

Unfortunately I noticed that the 64-bit version of **sh.exe** fails to run a command like:

    sh -c 'echo test'

which makes it completely useless in my setup, where make runs all children commands via sh.

The build script is documented in my [wiki](http://gnuarmeclipse.livius.net/wiki/How_to_cross_build_Windows_Build_Tools) page, part of the open-source [GNU ARM Eclipse plug-ins](http://gnuarmeclipse.livius.net/blog/) project. 

Any clues on what might be wrong?

**Comment by rmyorston** [comment] 2015-03-17 23:02
Sorry, I have no clues to offer.  With some help and encouragement I was able to get a 64-bit build to work, but I've never really tested it.

**Comment by ilg-ul** [comment] 2015-03-18 07:38
> I was able to get a 64-bit build to work,

in my script all I had to do was to reconfigure `CONFIG_CROSS_COMPILER_PREFIX="x86_64-w64-mingw32-"`, and the build passed as usual (with lots of warnings...).

I might be wrong, but I had the feeling that a 64-bit version of BusyBox already runs in some environments like MSYS2, or alike, so there should be not *Mission Impossible* to make yours run too.

**Comment by tkelman** [comment] 2015-04-01 21:19
I've also been interested in trying to get this to work eventually.

> I had the feeling that a 64-bit version of BusyBox already runs in some environments like MSYS2

From what I can see, the MSYS2 version of busybox is an msys package, meaning it relies on the posix layer a la cygwin, rather than a mingw package that calls the native API's like this port.

**Comment by rmyorston** [comment] 2015-07-03 13:40
The problem with the 64-bit build seems to be the same issue with environment manipulation that caused busybox-w32 to fail on ReactOS.  This was fixed for ReactOS by commit fa147bd but that was reverted because it broke Windows XP (issue #29).

So, I've reintroduced the fix but have made it a configuration option. The default 32-bit configuration uses the unsafe environment manipulation (so it works on Windows XP) while the default 64-bit configuration uses the safe code.

**Comment by ilg-ul** [comment] 2015-07-03 15:46
if I got it right, I have to do nothing special, since you automatically add `SAFE_ENV` for win64. is this correct?

**Comment by rmyorston** [comment] 2015-07-03 15:54
I added a new default configuration, so `make mingw64_defconfig` will set the 64-bit compiler prefix and the correct value for the `SAFE_ENV` option.

**Comment by ilg-ul** [comment] 2015-07-03 15:57
ok, thank you, I'll give it a try these days and let you know the results.

**Comment by rmyorston** [comment] 2015-07-14 13:07
I've made another tweak to the default configuration for the 64-bit build:  it appears that the compiler options to enable unwind tables are required, otherwise `setjmp`/`longjmp` don't work.

**Comment by ilg-ul** [comment] 2015-07-14 13:12
you mean c++ exceptions? this is tricky, there are two ways to implement exceptions in c++ (setjmp/longjmp vs tables), and various mingw toolchains use different settings for this. the applications should use the same setting as the toolchain.

**Comment by rmyorston** [comment] 2015-07-14 13:17
No, there isn't any C++ in BusyBox.  `setjmp`/`longjmp` are used for error handling in the shell.

**Comment by ilg-ul** [comment] 2015-07-14 13:21
then what unwind tables are you referring to? if I remember right, the setjmp/longjmp mechanism should be portable.

**Comment by rmyorston** [comment] 2015-07-14 13:26
The default `CFLAGS` for BusyBox includes the compiler options `-fno-unwind-tables` and `-fno-asynchronous-unwind-tables` with the comment that these "defeat .eh_frame bloat".  Perhaps they do, but in the 64-bit build they have the side effect of breaking `setjmp`/`longjmp`.

**Comment by ilg-ul** [comment] 2015-07-14 13:32
'eh' in that comment means 'exception handling', and the 'frame bloat' refers to using lots of tables to help unwind exception stack frames. probably these options interfere with the way BusyBox uses setjmp/longjmp.

**Comment by ilg-ul** [comment] 2015-07-15 19:01
I did a test and compiled commit 9fe16f6, but the 64-bits version of sh.exe still not does not run properly when called by make. exactly the same build for the 32-bits version generates a functional sh.exe.

```
make all 
Building file: ../system/src/stm32f4-hal/stm32f4xx_hal.c
Invoking: Cross ARM C Compiler
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DUSE_FULL_ASSERT -DOS_USE_SEMIHOSTING -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -DSTM32F407xx -DUSE_HAL_DRIVER -DHSE_VALUE=8000000 -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/stm32f4-hal" -std=gnu11 -MMD -MP -MF"system/src/stm32f4-hal/stm32f4xx_hal.d" -MT"system/src/stm32f4-hal/stm32f4xx_hal.o" -c -o "system/src/stm32f4-hal/stm32f4xx_hal.o" "../system/src/stm32f4-hal/stm32f4xx_hal.c"
116
system/src/stm32f4-hal/subdir.mk:51: recipe for target 'system/src/stm32f4-hal/stm32f4xx_hal.o' failed
make: *** [system/src/stm32f4-hal/stm32f4xx_hal.o] Error 244
```

apparently it returns 116.

however it seems slightly better than the previous version I used, since 
```
sh -c "echo test"
```
now seems ok.

the build procedure I use is unchanged, it just calls ```make```.

should I add anything special for the 64-bits build?

**Comment by rmyorston** [comment] 2015-07-15 19:52
I just use `make mingw64_defconfig; make` to build the 64-bit binary.

Can you reproduce the problem outside the `make all`?

**Comment by ilg-ul** [comment] 2015-07-15 20:26
> make mingw64_defconfig

aha! you already told me that, but I forgot...

with this change the 64-bits version seems functional.

do you have any changes planned for the next days? could you notify me when you have a new stable version that I can use for my next public release? (tentative release date set for the end of this month).

**Comment by rmyorston** [comment] 2015-07-15 20:38
Splendid! I'm glad it seems to be working now.

I don't have any immediate changes planned.  There's never really a stable version: I make changes as I see fit and merge with the upstream development branch from time to time.  The commit you've used is currently as good as it gets: it has the latest 64-bit fixes and is up-to-date with upstream.  If it works, use it.  And if it doesn't, let me know and I'll see what I can do.

**Comment by rmyorston** [comment] 2015-10-15 09:07
Three months with no feedback, let's close this.

**Closed by rmyorston** 2015-10-15 09:07 UTC

**Comment by ilg-ul** [comment] 2015-10-15 09:09
I have no complains from GNU ARM Eclipse users, so it should be ok.
