### ISSUE TITLE
Use FileIndex in place of inode number

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#141] opened 2019-02-15 08:17 UTC
Hi,
on Windows there is `FileIndex` that is like inode number, it would be nice to show it inside `ls`.

Ref: https://stackoverflow.com/questions/7162164/does-windows-have-inode-numbers-like-linux

**Comment by rmyorston** [comment] 2019-02-15 09:31
Yes, I know about ```FileIndex```. The same API also allows access to ```nNumberOfLinks``` which would be useful too.

The problem is that obtaining this additional information requires opening a handle to the file. You'll recall what happened when I was opening DLLs to see if they were shell scripts (issue #101): listing files became horribly slow.

If I *really* had to get an inode number or number of links I could use that API but it would have to be a special case in the code, not something that's done in the default implementation of ```stat(2)```.

**Comment by ale5000-git** [comment] 2019-02-15 11:26
Maybe it could be used only if specificallt required, ie using `-i` parameter of `ls`

**Comment by rmyorston** [comment] 2019-02-16 13:16
Performance isn't as bad as in the previous case: it's only necessary to open a handle to the file, no data needs to be read from it. I think the trade-off is probably worthwhile given the additional features it enables. See the commit message for d82db8e9a for details.

I've put a test binary here: [busybox_stat.exe](https://frippery.org/files/busybox/busybox_stat.exe). Give it a go and let me know what you think.

Currently the feature is configurable and enabled by default. If it hurts performance too much it could be disabled in the default build.

**Comment by ale5000-git** [comment] 2019-02-18 08:39
Sorry for the wait.
Listing c:\windows\system32 for the first time with `ls -i` take 4 seconds, it is still a good time.

The only problem is this:
```
ls: ./config: Permission denied
ls: ./Msdtc: Permission denied
ls: ./NetworkList: Permission denied
```

**Comment by rmyorston** [comment] 2019-02-18 16:18
Yes, the need to open a handle to the file to get the additional metadata leads to some non-Unix-like behaviour. I haven't found a way round this.

**Comment by ale5000-git** [comment] 2019-02-19 08:51
@rmyorston

This is probably why it happens:
dwShareMode => FILE_SHARE_READ => If this flag is not specified, but the file or device has been opened for read access, the function fails.
dwShareMode => FILE_SHARE_WRITE => If this flag is not specified, but the file or device has been opened for write access or has a file mapping with write access, the function fails.

So I suggest:
CreateFile(file_name, 0, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL|FILE_FLAG_BACKUP_SEMANTICS|FILE_FLAG_POSIX_SEMANTICS, NULL)

I haven't tried but it may works.

PS: I have also added FILE_FLAG_POSIX_SEMANTICS that enable support for case sensitive filenames for file systems that support that naming.

**Comment by rmyorston** [comment] 2019-02-19 10:32
>This is probably why it happens:

No, that's not it. Files aren't being opened for read or write because we only need to access their metadata: dwDesiredAccess is 0. I've tried many variations in the arguments to ```CreateFile``` and none is any better than the current combination.

>I have also added FILE_FLAG_POSIX_SEMANTICS

I won't be doing that:
- most filesystems on Windows aren't case sensitive;
- proper support for case sensitive filenames goes *way* beyond ```stat(2)```;
- there is zero chance of anything Microsoft have done to support POSIX being bug free.

Here's the current state of play.

There are two ways in which accessing the additional metadata fails:
- in most cases the error is ```ERROR_ACCESS_DENIED``` and the problem goes away if you have administrator privileges (except for C:/System Volume Information);
- for hiberfil.sys and pagefile.sys the error is ```ERROR_SHARING_VIOLATION``` and even being administrator doesn't help.

I haven't found any way to avoid these errors. So now I ask myself: what if we just ignore them?

There are hundreds of calls to ```stat(2)``` in BusyBox and most of them don't care about the additional metadata we're trying to fetch here. Very often the calls are made to answer simple questions like "Does this file exist and is it a regular file?". Causing ```stat(2)``` to fail just because we're unable to get the additional metadata breaks all these simple cases. (Admittedly only for files we're not going to be able to access anyway, but the program might never need to do that and even if it does it'll probably be able to issue a more relevant error message if it's allowed to get that far.)

What are the consequences if we let ```stat(2)``` succeed if we can't fetch the additional metadata? It'll still return correct information for everything most callers care about, only the inode number, device id and number of hard links will be incorrect.
- ```ls``` won't issue errors for files that ```stat(2)``` can't access, it'll just display an inode number of 0.
- Even with the current changes the number of hard links is wrong for directories; making it more wrong in a small number of cases isn't going to hurt too much.
- More significant is the use of the inode number/device id combination to determine if two files are
identical. However, there are relatively few such cases and they can be hacked so that invalid inode numbers are ignored. That's what I'm currently looking at.

**Comment by rmyorston** [comment] 2019-02-19 11:08
New test binary: [busybox_stat2.exe](https://frippery.org/files/busybox/busybox_stat2.exe).

**Comment by ale5000-git** [comment] 2019-02-25 16:52
Sorry for the time, I didn't had time to reply because I'm a bit busy, but your current solution of ignore errors seems to be the best way to handle these cases.

It seems to work fine but I will do other tests when I have some time.

**Comment by rmyorston** [comment] 2019-03-01 09:13
I've extended ```stat(2)``` further. It now tries to determine if files belong to the current user. If they don't it says they belong to root. This is slightly more useful than claiming that all files belong to the current user.

Test binary: [busybox_stat3.exe](https://frippery.org/files/busybox/busybox_stat3.exe).

**Comment by ale5000-git** [comment] 2019-03-01 14:25
It seems to work correctly but it would be nicer to get also the SID of other users in `ls -n`.

**Comment by rmyorston** [comment] 2019-03-01 14:45
Sure, but SIDs are big binary blobs that don't fit in a ```uid_t```.

**Comment by ale5000-git** [comment] 2019-03-01 16:26
You can use only the last part, example:
```
S-1-5-21-4244121947-2491301580-224350610-500 => 500
S-1-5-21-4244121947-2491301580-224350610-1000 => 500
S-1-5-21-4244121947-2491301580-224350610-1004 => 1004
S-1-5-21-4244121947-2491301580-224350610-1002 => 1002
```

**Comment by rmyorston** [comment] 2019-03-02 13:29
OK, try this one: [busybox_stat4.exe](https://frippery.org/files/busybox/busybox_stat4.exe).

When a SID looks like a local (or domain) user and the last part (the relative identifier, RID) looks reasonable ```stat(2)``` will set the uid to the RID.

Cygwin has a write-up on [POSIX accounts, permission, and security](https://cygwin.com/cygwin-ug-net/ntsec.html) which goes into great detail.

**Comment by ale5000-git** [comment] 2019-03-02 21:40
The RID of my current user is 1001 but it report 4095 (instead the username reported is correct).
The other user have RID of 1003 and it is displayed correctly as uid but the number is displayed also as username.

I'm not sure why, is there anything that I can do to help debugging?

**Comment by rmyorston** [comment] 2019-03-02 22:28
No debugging required, that's working as intended.

The current user is special and has a hardcoded uid: they might not have a local or domain SID but still need a uid.

Other local and domain users only have a uid, no name, so that's what ```ls``` displays. These uids might not be unique so it isn't possible to determine the associated name.  For that we'd need the whole SID (and, possibly, a callback to the domain controller).

**Comment by ale5000-git** [comment] 2019-03-02 22:38
I would have liked more to have a reported UID constant when `ls` is used on different users.

**Comment by rmyorston** [comment] 2019-03-28 08:21
The original request has been satisfied and a number of other unrelated features have been added. These are available in the current binary.

Time to close this.

**Closed by rmyorston** 2019-03-28 08:21 UTC
