### ISSUE TITLE
for applets that dont conflict with default windows programs, a program of the same name in PATH should be used instead of busybox when in ash

### ISSUE THREAD

**Issue by OldWorldOrdr** [rmyorston/busybox-w32#329] opened 2023-06-01 23:03 UTC
Some busybox programs should take priority over windows programs, like `find` for example, but others should try to use whatever is in PATH if there's something there, like `xz` or `wget`

The best solution would probably be to use whatever is in PATH when possible, but have a blacklist of command paths that should be overridden like `C:/Windows/System32/find.exe`

another solution would be to just allow programs installed from scoop or msys2 to override busybox commands

**Comment by rmyorston** [comment] 2023-06-02 05:59
The environment variable `BB_OVERRIDE_APPLETS` can contain a space-separated list of applets that are not to be used.

Thus if you want to use third-party copies of `xz` and `wget` you can set `BB_OVERRIDE_APPLETS="xz wget"`.

**Comment by avih** [comment] 2023-06-02 06:56
> The environment variable BB_OVERRIDE_APPLETS can contain a space-separated list of applets that are not to be used.

This has come up more than once. While it's useful to disable some applets, I think it would be nicer to use if a list of applets to instead be set lower priority than those in `$PATH`.

It could even use the same name, because the current behavior is as if the name was `BB_DISABLE_APPLETS`, while `OVERRIDE` suggests PATH overrides applets, but if none is in PATH - do use the applet.

For what it's worth, that's my current implementation of this concept, to be placed at `~/.profile`:
```sh
BB_PREFER_EXTERNAL="ar less make strings vi xxd"

# implement/apply BB_PREFER_EXTERNAL: disable applets if they exist externally.
# note: applets stay disabled even if their availability changes later.
[ -z "${BB_PREFER_EXTERNAL-}" ] || [ "${BB_OVERRIDE_APPLETS+x}" ] \
||  export BB_OVERRIDE_APPLETS="$(
        for x in $BB_PREFER_EXTERNAL; do
            export "BB_OVERRIDE_APPLETS=$x"
            command -v "$x" >/dev/null && printf "%s " "$x"
        done
    )"
```

**Comment by rmyorston** [comment] 2023-06-02 16:20
I can see value in having it work both ways. But I didn't want to:
- change the existing documented behaviour of `BB_OVERRIDE_APPLETS`;
- introduce any new variables.

So I've extended how `BB_OVERRIDE_APPLETS` works in a backwards compatible manner.

- Applet names in the list can be separated by spaces, commas or semicolons.
- Applets before the first semicolon are disabled unconditionally.
- Applets after the first semicolon are overridden if a matching external command exists.
- `-` alone disables all applets.   
- `+` alone overrides every applet for which a matching external command exists.

The example above can be represented as `BB_OVERRIDE_APPLETS=";ar less make strings vi xxd"`.

There are new [prereleases](https://frippery.org/files/busybox/prerelease), of course.

**Comment by avih** [comment] 2023-06-02 17:06
Very nice. Thanks.

**Comment by avih** [comment] 2023-06-02 17:38
> Very nice. Thanks.

But I think it's at least somewhat not working as intended:

```sh
$ export BB_OVERRIDE_APPLETS="; make ar"
$ which make
D:/run/w64devkit/1.19.0/bin/make.exe
$ make --version
make: unknown option -- version
BusyBox v1.37.0.git.FRP-5007-g82accfc19-6.....
$ make.exe --version
GNU Make 4.4.....
```

So because `make` is invokable from the path, I'd expect it to override the applet?

**Comment by ale5000-git** [comment] 2023-06-02 20:17
@rmyorston
This thing is really really really really really really really really really useful.
Is there any hope to have it upstream?
I would really like it landed on both  Linux and Android.

**Comment by OldWorldOrdr** [comment] 2023-06-02 23:26
would be nice to have it be able to act as a whitelist instead of blacklist, like have the behavior of "+" but still let a few commands override like `find`

**Comment by rmyorston** [comment] 2023-06-03 07:03
@avih The shell caches path look-ups. Since `BB_OVERRIDE_APPLETS` can now affect the result of path look-ups it may be necessary to invalidate the cache when it changes. I've taken the simple approach of doing that on every change. I don't expect `BB_OVERRIDE_APPLETS` to change regularly. (Though I'm sure somebody will prove me wrong eventually.) You where the prereleases live.

@ale5000-git Three emojis and nine 'really's. I may be wrong but I think you like it.

I suppose it _could_ go upstream, but some work would be needed. I've gone overboard with `BB_` environment variables in busybox-w32 so there's some infrastructure which isn't upstream and would be overkill for just one.

I'm also not sure it would be as useful there. Do Linux and Android versions of BusyBox enable standalone shell mode? I don't recall seeing it there.

@OldWorldOrdr My initial thought is that the complexity isn't worth it. For the odd command like `find` it might be simpler just to do it the old-fashioned way and have a link to busybox-w32 `find` in a `PATH` directory which precedes Windows `find`.

**Comment by avih** [comment] 2023-06-03 08:09
> @avih The shell caches path look-ups. Since `BB_OVERRIDE_APPLETS` can now affect the result of path look-ups it may be necessary to invalidate the cache when it changes

Not sure whether this implies something on my test case above, but I initialy noticed it when I set `BB_OVERRIDE_APPLETS="; ar make [...]"` at `~/.profile` where `make` definitely was not invoked prior, and on the first invocation of `make` from the CLI it invoked the applet rather than `make.exe`, and then I synthesized the test case above.

So I don't immediately see how the cache was involved here.

Also, with the latest commit e013876e I still can't get it to work when set via `~/.profile`.

Here's my entire `~/.profile`:
```sh
export "PATH=d:/run/w64devkit/1.19.0/bin;$PATH"  # has ar.exe, make.exe, etc
export "BB_OVERRIDE_APPLETS=; ar make strings xxd"
```

Then I run `busybox sh -l`, and here's the CLI session:
```
~ $ which make
d:/run/w64devkit/1.19.0/bin/make.exe
~ $ make --version
make: unknown option -- version
BusyBox v1.37.0.git.FRP-5007-g82accfc19-7.....
~ $ make.exe --version
GNU Make 4.4.....
~ $ echo $BB_OVERRIDE_APPLETS
; ar make strings xxd
```

**Comment by rmyorston** [comment] 2023-06-03 11:43
@avih I was puzzled by the test case because it worked fine as provided. It took a bit of experimentation to get something similar to fail. The resulting fix is required.

The problem is with `PATH`, which I didn't change in my testing.

If the status of an applet depends on whether or not a corresponding external command exists we need to perform a `PATH` search to determine that. Currently this uses the `PATH` environment variable.

The shell, however, plays various games with paths, so using the environment variable is insufficient to match its behaviour. I'm still investigating how to proceed from here.

**Comment by ale5000-git** [comment] 2023-06-03 12:39
> @ale5000-git Three emojis and nine 'really's. I may be wrong but I think you like it.
> 
> I suppose it _could_ go upstream, but some work would be needed. I've gone overboard with `BB_` environment variables in busybox-w32 so there's some infrastructure which isn't upstream and would be overkill for just one.
> 
> I'm also not sure it would be as useful there. Do Linux and Android versions of BusyBox enable standalone shell mode? I don't recall seeing it there.
> 
:)

About Linux I don't know exactly, but given the infinite amount of Linux distributions I bet there are some of them configured in this way.

About Android I think new ROM doesn't ship BusyBox by default but there are many useful cases:
- Flashable zips for Android could ship a BusyBox inside themself (standalone shell mode is really useful here).
- Magisk (Magisk is a suite of open source software for customizing Android, it also provide a sytemless root) also ship a BusyBox.

The BusyBox included inside Magisk provide an envoronment variable ASH_STANDALONE that is similar to standalone shell mode but work at runtime, the main disavantage is the missing granularity (just 0 or 1).

So if your code could replace the ASH_STANDALONE custom code and have it available also in all OSes it would really be nicer.

**Comment by ale5000-git** [comment] 2023-06-03 12:47
If the code while going upstream gets little differences and/or use a different variable name I personally doesn't care too much since it isn't hard to fix the places where I use it.
I would like to also know the opinion of others but I don't think it create many problems to people using it if it needs changes; it will also simplify maintenance by reducing upstream differences.

**Comment by rmyorston** [comment] 2023-06-04 07:52
@avih As mentioned above, the problem is with the use of the `PATH` environment variable.

If the `PATH` _shell_ variable is updated it's exported to the environment when a command is run, so they work fine. However, code _within_ the shell uses the shell version of `PATH`. This needs to be passed to the applet look-up code.

As well as determining which version of `make` is run (to use your example) this also affects `command -p` and the `help` shell built-in. Tab-completion isn't affected.

There's a new prerelease which should fix these issues.

**Comment by avih** [comment] 2023-06-04 08:57
> This needs to be passed to the applet look-up code.

Right, the patch seem more extensive than I hoped due to that, passing the path around.

Apologies for not giving a batter test case initially. Glad you figured it out anyway.

This seems to now work as expected in my testcase where PATH is modified at `~/.profile`, for invocation, `type`, `command -v` (finding the external one), `help` and `command -p` (behave as if it doesn't exist).

I've never used `command -p` before, but my feeling is that the behavior for this case is open to interpretation (it's certainly not specified anywhere how BB_OVERRIDE_APPLETS or similar should affect `command -p`), and I assume your interpretation - where it behaves as if the command is not found - is reasonable.

Thanks again.

**Comment by rmyorston** [comment] 2023-12-28 08:25
The revised version of `BB_OVERRIDE_APPLETS` has been in the last two releases: time to close this.

**Closed by rmyorston** 2023-12-28 08:25 UTC
