### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by j16180339887** [rmyorston/busybox-w32#114] opened 2018-04-27 02:06 UTC
It would be nice to have a choco package of busybox.

Something like `choco install busybox` to install it.

Is this on the roadmap? thanks :)

**Comment by rmyorston** [comment] 2018-04-27 07:55
This is a duplicate of issue #24.

The situation hasn't changed since then: this isn't something I'm planning to work on.

**Closed by rmyorston** 2018-04-27 07:55 UTC

**Comment by j16180339887** [comment] 2018-04-27 08:05
Thanks, I will try scoop instead of chocolatey.
