### ISSUE TITLE
Busybox-w32 freeze when pressing TAB on a new line.

### ISSUE THREAD

**Issue by whileloopa** [rmyorston/busybox-w32#204] opened 2020-12-10 06:16 UTC
If there is nothing or only space chars before the TAB key, Busybox-w32 just freeze and cause high cpu usage.

**Comment by rmyorston** [comment] 2020-12-10 08:44
I'm unable to reproduce this. What's in your ```PATH```?

Try [this](https://frippery.org/files/busybox/prerelease/busybox_tab_completion.exe) binary: it prints all the locations that are searched during tab completion.

It's built from current HEAD (commit 26b641cde) with this patch:

```diff
diff --git a/libbb/lineedit.c b/libbb/lineedit.c
index b35da1874..1cc422bb0 100644
--- a/libbb/lineedit.c
+++ b/libbb/lineedit.c
@@ -936,6 +936,7 @@ static NOINLINE unsigned complete_cmd_dir_file(const char *command, int type)
 
 #if ENABLE_PLATFORM_MINGW32
 			found = concat_path_file(lpath, name_found);
+fprintf(stderr, "%s\n", found);
 #else
 			found = concat_path_file(paths[i], name_found);
 #endif
```

**Comment by whileloopa** [comment] 2020-12-10 11:34
The PATH environment variable is
`C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0;D:/Apps;D:/Apps/CmdTool;C:/Program Files/Disktrix/UltimateDefrag;` 
The busybox.exe downloaded from homepage freeze without showing anything.
The busybox_tab_completion.exe above list many files before freeze.

If I remove the D:/Apps component from PATH variable, then everything OK.
D:/Apps contain 280 files and 270 folders.

**Comment by whileloopa** [comment] 2020-12-10 12:02
Problem solved.
There are two symbolic link files in D:/Apps, which cause Busybox-w32 to freeze.

**Comment by avih** [comment] 2020-12-10 12:57
> Problem solved.
> There are two symbolic link files in D:/Apps, which cause Busybox-w32 to freeze.

Sounds more like an actual issue that busybox-w32 freezes on some symbolic links?

**Comment by rmyorston** [comment] 2020-12-10 13:09
Possibly.

@whileloopa What exactly were the problematic symbolic links?

**Comment by rmyorston** [comment] 2020-12-10 13:31
This may or may not be related. I've found a bug in upstream BusyBox: when searching ```PATH``` for binaries during tab completion directories are being matched, which is incorrect.

I've put a fixed busybox-32 [here](https://frippery.org/files/busybox/prerelease/busybox_tab_completion2.exe).

Patch:
```diff
diff --git a/libbb/lineedit.c b/libbb/lineedit.c
index b35da1874..a0c0374af 100644
--- a/libbb/lineedit.c
+++ b/libbb/lineedit.c
@@ -945,6 +945,9 @@ static NOINLINE unsigned complete_cmd_dir_file(const char *command, int type)
 			if (stat(found, &st) && lstat(found, &st))
 				goto cont; /* hmm, remove in progress? */
 
+			if (type == FIND_EXE_ONLY && !dirbuf && S_ISDIR(st.st_mode))
+				goto cont;
+
 # if ENABLE_PLATFORM_MINGW32
 			if (type == FIND_EXE_ONLY && !S_ISDIR(st.st_mode) &&
 					!file_is_executable(found))
```

**Comment by avih** [comment] 2020-12-10 13:47
> I've found a bug in upstream BusyBox: when searching PATH for binaries during tab completion directories are being matched, which is incorrect.

How's this incorrect? tab completion is highly useful when it completes directories...

**Comment by rmyorston** [comment] 2020-12-10 14:37
Suppose ```/bin``` is on ```PATH``` and the file ```/bin/foo/bar``` exists. A user can type:
```
  $ fo<TAB>
```
```foo/``` shouldn't be included as a match because when the command contains a slash the shell won't use ```PATH``` to execute it.

**Comment by avih** [comment] 2020-12-10 15:25
Right. Thanks. Originally I misunderstood where it's applied.

**Comment by whileloopa** [comment] 2020-12-10 18:16
I suggest search files with extension in PATHEXT environment variable plus the ".sh" extension.

The symbolic links are link to .exe files and the symbolic links themselves also have .exe extension. You can try this
```
mklink cmd_sym.exe $(where cmd.exe)
ls.exe cmd*          # no problem
ls cmd*              # busybox freeze
```

**Comment by rmyorston** [comment] 2020-12-11 09:07
>I suggest search files with extension in PATHEXT environment variable plus the ".sh" extension.

Is this related to the current problem? If not I'd prefer it to be a separate issue. I did look into ```PATHEXT``` in issue #126.

>The symbolic links are link to .exe files and the symbolic links themselves also have .exe extension. 

I still can't reproduce the problem. At an administrator command prompt I ran:
```
mklink C:\Windows\System32\cmd_sym.exe C:\Windows\System32\cmd.exe
```
In the busybox-w32 shell pressing TAB on a new line didn't freeze and ```ls C:/Windows/System32/cmd*``` worked as expected. I get the same results on Windows 8.1 and 10 using the current busybox-w32 release, FRP-3578-g359211429.

**Comment by rmyorston** [comment] 2020-12-12 13:53
OK, I made a Windows 7 virtual machine and was able to reproduce the problem.

There was an infinite loop in code to handle symbolic links when the symbol ```GetFinalPathNameByHandleA``` couldn't be loaded. I don't know why it can't be found in Windows 7 as it was introduced in Vista.

The latest prerelease binary from [here](https://frippery.org/files/busybox/prerelease) should fix the issue. On systems that don't have (or can't load) the required symbol there will be a slight reduction in functionality relating to symbolic links.

**Comment by rmyorston** [comment] 2021-01-19 08:43
Release FRP-3812-g12e14ebba includes the fix. Closing.

**Closed by rmyorston** 2021-01-19 08:43 UTC
