### ISSUE TITLE
UTF8 and classic terminal on windows

### ISSUE THREAD

**Issue by hummeleBop** [rmyorston/busybox-w32#203] opened 2020-12-05 08:40 UTC
Hi everyone,

I'm playing with powershell and busybox in a Windows Terminal tab.

``` powershell
	$OutputEncoding = [Text.UnicodeEncoding]::New(
		<# bigEndian #> $FALSE, <# byteOrderMark #> $FALSE, <# throwOnInvalidBytes #> $TRUE
	)
	'Hello world, Καλημέρα κόσμε, コンニチハ' |
	  & \programs\busybox\busybox64.exe --% bash -c "cat - | iconv -f UTF16 -t UTF8 1>output.txt"
```

As expected, the previous code writes «Hello world, Καλημέρα κόσμε, コンニチハ» (using the utf8 charset) in the file output.txt 

However when I try to display the same content in the terminal, it doesn't work :

``` powershell
	$OutputEncoding = [Text.UnicodeEncoding]::New(
		<# bigEndian #> $FALSE, <# byteOrderMark #> $FALSE, <# throwOnInvalidBytes #> $TRUE
	)
	[Console]::OutputEncoding = [Text.UTF8Encoding]::New( <# encoderShouldEmitUTF8Identifier #> $FALSE)
	'Hello world, Καλημέρα κόσμε, コンニチハ' |
	  & \programs\busybox\busybox64.exe --% bash -c "cat - | iconv -f UTF16 -t UTF8"
```

The previous code prints the following content :

```
Hello world, IsI�I�I�I���3I?I� I���1I�I�I�, a,3a�3a�<a�?a�?
```

I also tried in a classic cmd terminal :

```
	chcp 65001
	echo Hello world, Καλημέρα κόσμε, コンニチハ | \programs\busybox\busybox64.exe bash -c "cat -"
```

The same result occurs.

Is there a way to display UTF8 characters in a windows terminal from busybox ?

Thanks a lot.

**Comment by hummeleBop** [comment] 2020-12-05 15:57
OK, I finally found an answer for this specific issue:

``` powershell
$OutputEncoding = [Text.UnicodeEncoding]::New(
	<# bigEndian #> $FALSE, <# byteOrderMark #> $FALSE, <# throwOnInvalidBytes #> $TRUE
)
[Console]::OutputEncoding = [Text.UTF8Encoding]::New( <# encoderShouldEmitUTF8Identifier #> $FALSE)
'Hello world, Καλημέρα κόσμε, コンニチハ' |
  & \programs\busybox\busybox64.exe --% bash -c "cat - | iconv -f UTF16 -t UTF8 | dos2unix"
```

I had to call dos2unix at the end of the busybox little script.

Now, the output is what it should be 👍

**Comment by rmyorston** [comment] 2020-12-07 08:59
busybox-w32 only supports single-byte encodings. For more on this see issues #17 and #135.

Top marks for finding the ```dos2unix``` workaround. Unfortunately ```dos2unix``` shouldn't be doing that and will be fixed in a future release.

**Comment by hummeleBop** [comment] 2020-12-07 10:33
OK Fine, however I think this feature is really important for the most interoperability.
Is there a way to enable an utility that could print UTF8 characters in the windows terminal ?
Something like « echo 'my utf8 characters' | asWinUTF8 »

I think it's really relevant for today's use.

Thanks a lot.

**Comment by avih** [comment] 2020-12-07 12:53
> Something like « echo 'my utf8 characters' | asWinUTF8 »

The problem is the input. The console integration in busybox-win32 just doesn't support unicode, so you can't type in unicode.

The windows console does support utf16, so if you have some UTF-8 content (e.g. which you typed into a script as a string with an editor which supports UTF-8, or a file encoded as UTF-8) then you can convert it to UTF-16 which the windows console will display:
```sh
echo "string with UTF-8 chars which was typed in an editor which supports utf-8" |  | iconv -f UTF-8 -t UTF-16LE
cat my-utf8-file.txt | iconv -f UTF-8 -t UTF-16LE
```

But in general, no, currently busybox-win32 doesn't support unicode, which can be especially limiting with file paths.

**Comment by avih** [comment] 2020-12-07 12:58
You can read this message and download an older version of busybox-win32 from git-for-windows which does support unicode - https://github.com/rmyorston/busybox-w32/issues/17#issuecomment-667582825

**Comment by hummeleBop** [comment] 2020-12-07 14:08
Hi thanks for your answer,

So let's try something in powershell

``` powershell
$OutputEncoding = [Text.UTF8Encoding]::New($FALSE)
"L'ÉTUI" | & \programs\busybox\busybox64.exe --% bash -c "tr -d '\r\n' | xxd -p"
# It prints « c389545549 », the correct hexdecimal content for the input string as UTF-8

$OutputEncoding = [Text.UTF8Encoding]::New($FALSE)
[Console]::OutputEncoding = [Text.Encoding]::Unicode
"L'ÉTUI" | & \programs\busybox\busybox64.exe --% bash -c "tr -d '\r\n' | iconv -f UTF8 -t UTF16LE"
# It prints « L », It doesn't work as expected :(

# However the binary data is correct :
$OutputEncoding = [Text.UTF8Encoding]::New($FALSE)
[Console]::OutputEncoding = [Text.Encoding]::Unicode
"L'ÉTUI" | & \programs\busybox\busybox64.exe --% bash -c "tr -d '\r\n' | iconv -f UTF8 -t UTF16LE | xxd -p"
# It prints « 4c002700c900540055004900 »
```

**Comment by hummeleBop** [comment] 2020-12-12 17:29
Finally, it works well.

I did a mistake in my previous examples.

The following script works pretty well 👍 

``` powershell
$OutputEncoding = [Text.UTF8Encoding]::New($FALSE)
# data piped as utf8 string from powershell to the native cmd busybox command
[Console]::OutputEncoding = [Text.Encoding]::Unicode
# stdout from Busybox is an UTF16LE string
"L'ÉTUI" | & \programs\busybox\busybox64.exe --% bash -c "tr -d '\r\n' | iconv -f UTF8 -t UTF16LE" | Out-Host
# The last part « | Out-Host » is necessary to treat the output as an UTF16LE string, I don't know why though..
# Probably some intrinsics pwsh behaviors
# And the command prints « L'ÉTUI »
```

It can work with other encoding 👍 

``` powershell
$OutputEncoding = [Text.UTF8Encoding]::New($FALSE)
[Console]::OutputEncoding = [Text.UTF8Encoding]::New($FALSE)
# Everything in UTF8
'Hello world, Καλημέρα κόσμε, コンニチハ' | & \programs\busybox\busybox64.exe --% bash -c "cat -" | Out-Host
```

**Closed** 2020-12-12 17:36 UTC
