### ISSUE TITLE
shell does not detect user properly

### ISSUE THREAD

**Issue by hronro** [rmyorston/busybox-w32#300] opened 2023-03-26 05:47 UTC
I'm using `busybox ash` as my login shell.

As you can see in the screenshot, the environment variables `USER` `HOME` and `LOGNAME` are all set to `root` which is not correct, however the variable `USERNAME` is actually correct.

![Screenshot 2023-03-26 134226](https://user-images.githubusercontent.com/15059605/227757625-0461a28e-4a2b-4cd3-bd6c-1363a26d49d0.png)

**Comment by rmyorston** [comment] 2023-03-26 08:08
This is probably related to issue #240. TL;DR: when logging in remotely an admin user is granted elevated privileges which busybox-w32 reports by claiming to be the **root** user.

Are you logging in remotely? If so, how? I note you have a `LOGONSERVER` variable.

One new feature is the observation about `USERNAME`. For consistency this should be the same as `USER` and `LOGNAME`. I see other problems with these variables when dropping privilege, which I'll look into.

**Comment by hronro** [comment] 2023-03-26 10:56
I'm NOT login remotely.

I installed busybox via scoop and create a new busybox profile in my Windows Terminal like this:

![Screenshot 2023-03-26 185443](https://user-images.githubusercontent.com/15059605/227771031-fc90899c-56ab-40b9-9610-13d456356eed.png)

The `Command line` setting in Windows Terminal is `%UserProfile%\scoop\shims\busybox.exe ash -l`

**Comment by rmyorston** [comment] 2023-03-26 12:02
I'm unable to reproduce what you're seeing. I've installed busybox-w32 via scoop and have configured a profile in Windows Terminal exactly like yours. But when I start the terminal with that profile I get a normal, unprivileged session.

In your case the environment settings and `~ # ` prompt indicate that busybox-w32 has detected you're running with elevated privileges. I've no idea why.

**Comment by ale5000-git** [comment] 2023-03-26 21:25
@hronro
I suggest to try the latest prerelease from here: https://frippery.org/files/busybox/prerelease/?C=M;O=D
There are many fixes compared to the latest stable release.

**Comment by cochon-git** [comment] 2023-03-27 10:59
> `USERNAME` should now be consistent with `USER` and `LOGNAME`

This is 'probably' a good idea for consistency, but unlike $USER and $LOGNAME, seems a very Windows specific variable and unlikely to be used in generic scripts, it traditionally indicates the logged in username. Now it will be set to a fake 'root', what mechanism remains to determine the actual username? $USERPROFILE doesn't have to reflect the username.

**Comment by rmyorston** [comment] 2023-03-27 11:33
>what mechanism remains to determine the actual username?

It's not portable (like a lot of the stuff going on around here) but `drop -c 'id -un'` should do the trick, regardless of privilege.

**Comment by ale5000-git** [comment] 2023-03-27 14:44
This is easy to remember:
`drop whoami`

**Comment by rmyorston** [comment] 2023-06-05 10:57
On reflection I've decided it's probably best not to subject `USERNAME` to special treatment. That part of the earlier commit has been reverted.

**Comment by hronro** [comment] 2023-06-06 03:26
Update: I have just discovered that changing the UAC setting back to default has solved my issue. Previously, it was set to "never notify".

**Comment by rmyorston** [comment] 2023-06-06 09:11
@hronro Thanks for solving the mystery! I think we can close this now.

**Closed** 2023-06-06 09:11 UTC

**Comment by hronro** [comment] 2023-06-06 15:35
@rmyorston Is this a Windows problem rather than a Busybox issue? I'm not very familiar with the inner workings of Windows, but does setting UAC to "never notify" mean that programs cannot be executed without administrator privileges?

**Comment by rmyorston** [comment] 2023-06-06 18:34
>does setting UAC to "never notify" mean that programs cannot be executed without administrator privileges?

Apparently not. I've tried setting UAC to "never notify" and I don't see the behaviour you were getting. My shell runs with normal privileges.

So I don't know why changing the UAC setting back to default would make any difference in your case. Maybe something else was going on, but I've no idea what that might be.

What happens if you change back to "never notify"?
