### ISSUE TITLE
Build in Windows?

### ISSUE THREAD

**Issue by Hawk2811** [rmyorston/busybox-w32#239] opened 2022-01-08 06:27 UTC
I am unable to compile busybox on Windows 7 using LLVM-mingw and GNU Make

**Comment by rmyorston** [comment] 2022-01-08 07:50
I don't normally do development work on Windows but in the past I have been able to compile busybox-w32 on Windows 8 with MSYS2.

Do let us know if you manage to get it to work with LLVM.

**Comment by Hawk2811** [comment] 2022-01-08 07:53
> I don't normally do development work on Windows but in the past I have been able to compile busybox-w32 on Windows 8 with MSYS2.
> 
> Do let us know if you manage to get it to work with LLVM.

I'm not using msys2 because I compiled GNU Make from GnuWin32 straight from source code

**Comment by Shumen** [comment] 2022-08-26 15:19
is it possible to use TinyCC to build latest BusyBox-W32?

The old BusyBox-w32 can be built, see http://download.savannah.gnu.org/releases/tinycc/tcc-busybox-for-win32.zip

**Comment by rmyorston** [comment] 2022-10-24 11:08
@HuangShumin Many thanks for sharing your work on building busybox-w32 with w64devkit. Since @skeeto had the good taste to include busybox-w32 it's clearly by far the best Microsoft Windows development environment.

I don't know what's going on with windres but the problem lies in ```VERSIONINFO``` which can be turned off in the configuration.

The makefile clearly can't handle a colon in the current directory. It's possible to automate stripping off the drive, which should work in most cases.

I've amalgamated your modifications plus some of my own into a patch ([w64devkit-build-busybox.txt](https://github.com/rmyorston/busybox-w32/files/9851064/w64devkit-build-busybox.txt)). The procedure then reduces to:
1. Extract latest busybox-w32-master.zip and run w64devkit's busybox ash console
2. ```cd busybox-w32-master```
3. ```patch -p1 <w64devkit-build-busybox.txt```
4. ```make mingw64_defconfig```
5. ```make```

**Comment by skeeto** [comment] 2022-10-25 00:31
> it's clearly by far the best Microsoft Windows development environment.

Take out any hint of sarcasm and I agree. 😃 busybox-w32 ties it all together as an excellent UI centerpiece.

> I don't know what's going on with windres

Details: skeeto/w64devkit#35. In short, `windres` passes arguments through to `cpp` by building a POSIX shell command string for `popen(3)`. This is not done entirely correctly on any platform, but particularly affects Windows since that POSIX shell command goes to `cmd.exe` via [`_popen`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=msvc-170). It's the parentheses tripping it up in this case. (Definitely never use `windres` with untrusted arguments.)

**Comment by rmyorston** [comment] 2022-10-25 08:03
Thanks for the additional information. I've changed the way resources are created to avoid the arguments ```windres``` finds problematic.

With this change the patch doesn't need to disable ```VERSIONINFO```: [w64devkit-build-busybox-v2.txt](https://github.com/rmyorston/busybox-w32/files/9858276/w64devkit-build-busybox-v2.txt)

I'm considering updating the README to suggest using w64devkit rather than MSYS2 for native builds.

**Comment by avih** [comment] 2022-10-25 08:55
Very nice.

> With this change the patch doesn't need to disable `VERSIONINFO`: [w64devkit-build-busybox-v2.txt](https://github.com/rmyorston/busybox-w32/files/9858276/w64devkit-build-busybox-v2.txt)
> 
> I'm considering updating the README to suggest using w64devkit rather than MSYS2 for native builds.

This line (tested with the previous version of the patch):
```diff
+CURDIR := $(lastword $(subst :, ,$(CURDIR)))
```

While seemingly necessary (it does solve some issues which stem from path with `:` in it), also forces to build at drive C.

The CURDIR change makes it start with slash, the value ends at `srctree`, and later when `make` tries to run it it guesses it's supposed to be at drive C, and fails (the dir is at drive R)
```sh
$ pwd  # also echo $PWD
R:/foo/bar/busybox-w32

$ make mingw64_defconfig
  [... success]

$ make
  [...]
  GEN     include/bbconfigopts.h
sh: C:/foo/bar/busybox-w32/scripts/mkconfigs: not found
make: *** [Makefile:873: include/config/MARKER] Error 127
```

However, this is fixable with an invocation like so:
```sh
make srctree=. [-j8]
```

Just FYI.

**Comment by rmyorston** [comment] 2022-10-25 11:28
>when make tries to run it it guesses it's supposed to be at drive C

No, that's not make guessing, that's busybox-w32 doing what I told it to.

Back in the FRP-3578 release I went overboard with changes to paths starting with a slash, forcing them to use the Windows system drive rather than the current drive as they're supposed to. The intent was to allow Unix-style paths like ```/bin/sh``` to work even if ```/bin``` was actually on ```C:``` but you were in ```R:```.

This probably went too far. I'll look into toning it down a bit so paths starting with a slash behave in a more Windows-like manner.

**Comment by avih** [comment] 2022-10-25 11:39
> busybox-w32 doing what I told it to

Hmmm.. so `make` invokes `sh` with a path starting with slash, and busybox-w32 or ash assumes by design that it should be `C:` ?

Does this also happen with inner invocations like from sh or other applets?

**Comment by rmyorston** [comment] 2022-10-25 12:12
>Hmmm.. so make invokes sh with a path starting with slash, and busybox-w32 or ash assumes by design that it should be C: ?

It's more complicated than that. If the path starts with a directory that Unix traditionally uses for binaries and an executable isn't found there, busybox-w32 will search for an applet or an executable on ```PATH```.  If that doesn't work it'll try adding the contents of the ```BB_SYSTEMROOT``` environment variable, if it exists, or the system drive (which is probably ```C:```).

>Does this also happen with inner invocations like from sh or other applets?

Yes

**Comment by rmyorston** [comment] 2022-10-25 15:50
It bothered me that the binaries generated using w64devkit were so much larger than the ones cross-compiled on Linux. The issue is with the compiler feature tests in ```scripts/Kbuild.include```. These test whether the compiler supports, say, ```--flag``` by checking the result of running a command like:
```
    cc --flag -S -o /dev/null -xc /dev/null >/dev/null 2>&1
```
Unfortunately ```/dev/null``` doesn't exist on Windows so such tests always fail. The third instance of ```/dev/null``` above is handled by the busybox-w32 shell, so isn't a problem.

The tests can be made to work by rewriting the commands to look like:
```
    cc --flag -S -o - -xc - </dev/null >/dev/null 2>&1
```
With the latest patch ([w64devkit-build-busybox-v3.txt](https://github.com/rmyorston/busybox-w32/files/9861864/w64devkit-build-busybox-v3.txt)) the binaries generated on Windows are about the same size as on Linux, slightly smaller, in fact.

**Comment by rmyorston** [comment] 2022-10-26 12:14
I've reverted the changes that were causing w64devkit builds of busybox-w32 to fail when run from a drive other than the system drive. The latest [prerelease binary](https://frippery.org/files/busybox/prerelease) has this adjustment.

**Comment by avih** [comment] 2022-10-26 13:17
> I've reverted the changes that were causing w64devkit builds of busybox-w32 to fail when run from a drive other than the system drive. The latest [prerelease binary](https://frippery.org/files/busybox/prerelease) has this adjustment.

Nice, I can confirm it works, and building busybox-w32 using w64devkit now works at any drive letter, but not strictly out of the box.

The issue now is that mingw64_defconfig (and your PRE binary, and my build) now enables `make`, and this has priority over w64devkit's `make`, but it doesn't build with busybox `make`.

One way to work around it is to invoke `make.exe` instead of `make`, but this is a bit awkward.

I'll open a new issue because I had to work around this behavior also with a stand alone `less.exe` which I prefer over busybox `less`, and had to jump through some hoops for it to work.

**Comment by rmyorston** [comment] 2022-10-26 14:26
>w64devkit now works at any drive letter, but not strictly out of the box.

The busybox-w32 binary that comes with w64devkit is a specially tailored version with some applets disabled and a few minor patches. I'm sure the ```make``` applet will be disabled too, when that becomes an issue.

https://github.com/rmyorston/busybox-w32/issues/44#issuecomment-1237274402

**Comment by rmyorston** [comment] 2022-10-27 08:30
Another revision of the patch to fix some more things that bothered me: 
[w64devkit-build-busybox-v4.txt](https://github.com/rmyorston/busybox-w32/files/9877364/w64devkit-build-busybox-v4.txt)

- Once a binary had been built changing any file would cause a complete rebuild, which rather defeats the purpose of using ```make```. The problem was in ```split-include.c```. It ```popen```s ```find``` to get a list of include files. On Unix it uses a wildcard ```*``` but that doesn't work with Windows ```popen``` so the previous patches changes the ```*``` to a ```.```. But then the filenames have a leading ```./```, which isn't what was expected. Stripping that off fixes the problem.
- Various utilities (like ```split-include```) were being built every time ```make``` was run because the generated binaries had a ```.exe``` suffix whereas the makefile expected no suffix. Use a trick to build them without a suffix.
- The documentation couldn't be built because we lack some Perl hackery. Just skip it.

**Comment by rmyorston** [comment] 2022-10-30 11:20
The latest code in git builds in w64devkit without patching. It also fixes a problem that broke the build in MSYS2.

@Hawk2811 Sorry your issue has been hijacked by spam about other build platforms.

I've successfully built busybox-w32 with clang in MSYS2. The only change needed was to replace ```int ffs(int i);``` in include/mingw.h with ```#define ffs __builtin_ffs```. The same change was initially required for w64devkit but that's no longer necessary. (It was probably fixed by the changes to compiler option detection. It's possible some clang compiler flag would have a similar effect.)

**Comment by rmyorston** [comment] 2022-10-31 14:04
The issues with the clang-generated build of busybox-w32 appear to be related to ```longjmp(3)```. This is used a lot in the shell but even the ```test``` applet uses it to handle syntax errors: ```test 3 -eq w``` crashes, for example.

I'm no expert in MSYS2 and its various environments so it's entirely possible I did something wrong. I defer to the relevant experts in this matter.

**Comment by rmyorston** [comment] 2024-01-21 13:14
@Hawk2811 It's been possible to build busybox-w32 on Windows for a while now using [w64devkit](https://github.com/skeeto/w64devkit). However, your question was specifically about using [llvm-mingw](https://github.com/mstorsjo/llvm-mingw). If that is still relevant I'm happy to report that it's now possible with the latest source.

As well as llvm-mingw you'll also need to have some additional tools (like GNU make, as mentioned above). I've used w64devkit to provide those.

Here's a shell script that works for me. It'll need to be edited to suit your setup:
```sh
#!/bin/sh

# Build busybox-w32 binary using clang from llvm-mingw and other
# utilities from w64devkit.
#
#    https://github.com/mstorsjo/llvm-mingw
#    https://github.com/skeeto/w64devkit
#
# Run this script in the top directory of the busybox-w32 source tree.
#

# Location of LLVM toolchain (edit to suit)
LLVM="C:/Users/rmy/llvm-mingw-20231128-msvcrt-x86_64/bin"
# Location of other utilities (GNU make, etc)
UTIL="C:/Users/rmy/w64devkit/bin"

# Don't use busybox-w32 make or ar
export BB_OVERRIDE_APPLETS="make ar"
export PATH="$LLVM;$UTIL;$PATH"

# Alter cross-compilation prefix for x86_64 (default is aarch64)
make mingw64a_defconfig CROSS_COMPILE=x86_64-w64-mingw32-
make -j $(nproc) CROSS_COMPILE=x86_64-w64-mingw32-
```

**Comment by rmyorston** [comment] 2024-02-13 12:59
On further investigation it turns out llvm-mingw _does_ have GNU make, it just calls it `mingw32-make.exe`. This means it isn't necessary to use w64devkit to perform a clang build on Windows: llvm-mingw and busybox-w32 are sufficient. I was able to use the following script to build an aarch64 busybox-w32 binary on x86_64 Windows:
```sh
#!/bin/sh

# Build busybox-w32 binary using clang from llvm-mingw and other
# utilities from busybox-w32.
#
#    https://github.com/mstorsjo/llvm-mingw
#
# Links to busybox-w32 need to be installed so make can find the utilities.
#
#    mkdir ~/util
#    cp path/to/busybox.exe ~/util
#    cd ~/util
#    ./busybox --install
#
# Run this script in the top directory of the busybox-w32 source tree.
#

# Location of LLVM toolchain and busybox-w32 utilties (edit to suit)
LLVM="C:/Users/rmy/llvm-mingw-20231128-msvcrt-x86_64/bin"
UTIL="C:/Users/rmy/util"

# Don't use busybox-w32 make or ar
export BB_OVERRIDE_APPLETS="make ar"
export PATH="$LLVM;$UTIL;$PATH"

# Perform aarch64 build
mingw32-make mingw64a_defconfig
mingw32-make -j $(nproc)
```
And here's the good bit: the same script (edited to suit) **also** works on Windows on ARM, with the appropriate native busybox-w32 and llvm-mingw.

**Comment by avih** [comment] 2024-02-13 13:22
> On further investigation it turns out llvm-mingw _does_ have GNU make, it just calls it `mingw32-make.exe`

Yup. I considered the option that w64devkit might not be required, but never actually tested that. Nice.

> ```shell
> #    ./busybox --install
> ```

How should one get some help on what the `--install` options mean?

`busybox` and `busybox --install --help` both show the same synoptic
```sh
busybox --install [-s] [-u|DIR]
```

I'm guessing without any options it does hardlinks (which IIRC doesn't require admin?) and I presume `-s` does symlinks? (which does require admin).

I'm guessing `DIR` is the install target dir instead of `.`, but at which case what does `-u` do instead of `DIR` (if I understand the form correctly).

Are those documented someplace?

**Comment by rmyorston** [comment] 2024-02-13 13:35
>Are those documented someplace?

On the [busybox-w32](https://frippery.org/busybox) webpage.

**Comment by avih** [comment] 2024-02-13 13:57
> busybox --list-all

It works but undocumented, though the listed `--list-full` seem to do the same thing.

Kinda weird that some things would end up in `c:/bin` and some in `c:/usr/bin`, but I guess whatever.

> The --install option creates 'hard' links which are available on NTFS filesystems but not FAT. Adding the option -s creates symbolic links, but this may not work if you don't have the required privileges. 

Other than the fact that it would be nice to have it in this repo (and maybe also all the release notes and other docs which are currently-unique to the frimpery page), this is kinda not ideal, though on a minor level.

Because the hard link require reinstalling when updating busybox, while the symlinks only need replacing of the single binary, but do require privileges.

Did you consider a tiny wrapper similar to what w64devkit does? (even if not adopting its exact code, because it goes to great length to NIH libc and the ms crt, which some might find kinda meh, myself included)

**Comment by rmyorston** [comment] 2024-02-13 14:37
I misremembered the documented name of the option. Actually, `--list-anything-at-all` also works. This is inherited from upstream which just checks for `--list-` and says, "Yeah, good enough".

There probably isn't an ideal way to make applets available as external commands. There seem to be downsides to every suggestion.

**Comment by avih** [comment] 2024-02-13 14:47
What's the downside of the wrapper? I'd guess embedding it in the binary? (and building it in the first place?)

**Comment by rmyorston** [comment] 2024-03-03 08:26
It's taken a while and there have been a few distractions, but it should now be possible to build busybox-w32 on Windows with llvm-mingw.

**Closed by rmyorston** 2024-03-03 08:26 UTC
