### ISSUE TITLE
'cat' applet crashes

### ISSUE THREAD

**Issue by MatthieuR** [rmyorston/busybox-w32#62] opened 2016-08-16 12:58 UTC
Just found a file where 'cat' command crashes when executed on it.
Crash is quite severe as no escape sequence allows to resume to prompt.
Running from Windows cmd and running from Busybox shell both crash.

Notice that 'less' works well on same file.

Attached is the truncated file keeping just enough to demonstrate the issue.

[test.zip](https://github.com/rmyorston/busybox-w32/files/420273/test.zip)

**Comment by rmyorston** [comment] 2016-08-16 15:11
The file contains NUL characters which broke my console ANSI emulation code. I've skipped the ANSI emulation in such cases. Try the latest build.

**Comment by MatthieuR** [comment] 2016-08-16 15:52
Indeed latest build fixes the issue.
As a side effect I noticed that 'cat' my entire file then makes the console window extremely long to close (about 1 minute).
File is about 110 ko. Same behavior from cmd or Busybox shell.
Same behavior with 'less' also but can't remember if it was the same with previous build.
I tried with smaller file (#5ko) and bigger (#500ko) and it seems closing time is related to dumped file size.
I finally tried by piping my 110ko file to a 'grep' that only outputs a few lines and window almost close instantly. Thus it probably has something to do with character count in output buffer or something like that.
Anyway many thanks for amazingly fast fix !

**Comment by rmyorston** [comment] 2016-08-17 07:53
I'm unable to reproduce the slow close of the console window.  Which version of Windows are you using?

**Comment by MatthieuR** [comment] 2016-08-17 14:53
My OS is Win7 Pro SP1.
After fighting some hours trying to explain this behavior I shall surrender.
Killing all processes that was loading CPU during window closing doesn't change anything. Deactivating antivirus is useless too. Finding some clues on Internet I uninstalled MS Keyboard & Mouse Center and kept only one keyboard language installed ... same thing. Procexp and Procmon don't show anything that may help too.
Thereafter I noticed something using 'more'. I use ConEmu and in that case window closing is very long as described but whole file is 'more'd almost instantly (paging is immediate). I tried using only native Win cmd and in that case window closing is normally fast but 'more' paging is really slow. It looks like time spent in paging in that last case should be spent in closing window in the first one.

Finally some collateral remarks found during my intensive use:
- Applet list when running busybox.exe without any argument isn't up-to-date
- 'more' command is never listed. However it is available in busybox shell, but strangly not from a direct cmd call
- 'watch' command would be very useful for me :-)

**Comment by rmyorston** [comment] 2016-08-17 17:15
I don't  have access to Windows 7. We may have to give up on this problem.

There is a 'more' applet in BusyBox but it isn't enabled in my busybox-w32 builds. I think 'less' is better, so haven't bothered to make 'more' work on WIN32. The 'more' command you're seeing is probably the native Windows one.

Is there anything else you think is missing from the list?

I've looked at the 'watch' command from time to time, but haven't yet got it working.

**Comment by MatthieuR** [comment] 2016-08-18 09:07
Indeed 'cat'ing large binary files isn't of great usefulness for most usages so having it working (even with some speed issue) is enough. I'll tell you if I find the root cause later. Or maybe somebody else will do.

I don't think I see the native Windows 'more' because it works inside busybox shell. And for example 'dir' command doesn't work. Really guess busybox 'more' is reachable from inside shell but not from outside. Anyway that's not really an issue and I totally agree 'less' is better.
I just compared the command lists and don't see anything else missing, and all are consistent.

'watch' is for me the only missing feature that would be really useful. But already have to thank you a lot for your job on busybox that I (almost) daily enjoy.

**Comment by rmyorston** [comment] 2016-08-18 09:23
There's a difference between 'more' and 'dir': 'more' is an executable while 'dir' is built-in to cmd.exe.

If you run 'which more' from the BusyBox shell I expect you'll see something like 'C:/Windows/system32/more.com' whereas 'which dir' will return nothing.

Anyway, since the main issue has been dealt with I'll close this now.

**Closed by rmyorston** 2016-08-18 09:23 UTC

**Comment by ale5000-git** [comment] 2016-08-18 16:33
@MatthieuR: Inside "busybox sh" digit "more /?".
It works and confirm it is the Windows version since it is a Windows parameter.

dir isn't a file, it is just a command provided by command prompt.
Instead more (more.com) is a file inside the search path so it is found everywhere.

**Comment by ale5000-git** [comment] 2016-08-18 16:36
@MatthieuR: It is here => C:\Windows\System32\more.com
