### ISSUE TITLE
Writability inconsistency

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#280] opened 2023-01-11 10:11 UTC
This print fail:
`test -w 'C:/Users/MyUserName/Documents' && echo ok || echo fail`
But this print ok:
`touch 'C:/Users/MyUserName/Documents/TEST1' && echo ok || echo fail`

**Comment by rmyorston** [comment] 2023-01-11 13:14
It's a regression. It used to work properly until FRP-4264-gc79f13025.

The read-only attribute doesn't have it's normal meaning for directories. See [this](https://support.microsoft.com/en-us/topic/you-cannot-view-or-change-the-read-only-or-the-system-attributes-of-folders-in-windows-server-2003-in-windows-xp-in-windows-vista-or-in-windows-7-55bd5ec5-d19e-6173-0df1-8f5b49247165) Microsoft support document.

Fixed in the [latest prerelease](https://frippery.org/files/busybox/prerelease).

**Comment by ale5000-git** [comment] 2023-01-11 15:30
My previous example is now fixed but not this one:

This print fail:
`test -w 'C:/Users/MyUserName' && echo ok || echo fail`
But this print ok:
`touch 'C:/Users/MyUserName/TEST1' && echo ok || echo fail`

**Comment by rmyorston** [comment] 2023-01-12 15:36
The `test` applet in busybox-w32 is completely unmodified from the upstream version. It therefore makes all its decisions based on Unix file ownership and permissions. Or rather, my flaky approximation to Unix file ownership and permissions on Windows.

Mostly, any file that doesn't belong to the current user is treated as belonging to root. Home directories on Windows don't belong to the user; they belong to the 'system' user with SID S-1-5-18. Thus my home directory looks like this in busybox-w32:
```
~ $ ls -ld C:/Users/rmy
drwxrwxr-x   29 root     root         40960 Jan 12 14:55 C:/Users/rmy
```
Since it doesn't belong to me it's treated as belonging to root and I don't seem to have write permission. Of course, I do really. But that's as a result of ACLs associated with the directory, not its attributes or ownership.

I haven't found a satisfactory workaround for this yet. (Where by satisfactory I mean one that doesn't cost hundreds of bytes of bloat.)

**Comment by ale5000-git** [comment] 2023-01-12 15:58
Permissions on Windows are complicated but an approximation that cover most cases  (just for writability or maybe also for chmod) is:

If the folder has write access for current user or for the "everyone" user then is writable otherwise no (ignoring ownership completely since it doesn't make any difference which is the owner as long as the current user or everyone has write access).

**Comment by rmyorston** [comment] 2023-01-16 11:42
After much experimentation I've now got something that works. It costs 220-256 bytes, but that's about half the size of my earlier attempts.

As usual, there's a [new prerelease](https://frippery.org/files/busybox/prerelease) with this feature.

**Comment by avih** [comment] 2023-01-16 12:16
> It costs 220-256 bytes, but that's about half the size of my earlier attempts.

For what it's worth, while upstream busybox might have use cases where space is of utmost importance (though maybe these days less than a decade ago), I think for users of busybox-w32 binary size and/or memory usage is generally of less concern than usefulness and more correct behavior, within limits.

So while personally I don't need this improved functionality, IMVHO, it would have been worth 512 bytes too.

Obviously, if the same functionality can be had for less bytes, then that's a win anyway.

**Closed** 2023-03-23 13:02 UTC
